version: "2"

services:
  client:
    build: 
      context: ./yeelight-controller-client/
      #dockerfile: Dockerfile
      dockerfile: Dockerfile.raspberry-pi
    restart: unless-stopped
    network_mode: "host"
    
  api:
    build: 
      context: ./yeelight-controller-api/
      #dockerfile: Dockerfile
      dockerfile: Dockerfile.raspberry-pi
    restart: unless-stopped
    network_mode: "host"
  
  fbcp:
    image: balenablocks/fbcp
    privileged: true

  browser:
    restart: unless-stopped
    build:
     context: ./browser/
     dockerfile: Dockerfile 
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: "host"
    environment:
      KIOSK: 1
      WINDOW_SIZE: 480,320
      LOCAL_HTTP_DELAY: 120
      ENABLE_GPU: 1
    ports:
        - '5011' # management API (optional)
        - '35173' # Chromium debugging port (optional)
