version: "2"

services:
  client:
    build: 
      context: ./yeelight-controller-client/
    #  dockerfile: Dockerfile
      dockerfile: Dockerfile.raspberry-pi
    restart: unless-stopped
    network_mode: "host"

    depends_on:
      - api
    
  api:
    build: 
      context: ./yeelight-controller-api/
    #  dockerfile: Dockerfile
      dockerfile: Dockerfile.raspberry-pi
    restart: unless-stopped
    network_mode: "host"
